Add Copyright licenses that can't be directly scraped
oppia/oppia-android-licenses pull request #1
Opened 2021-07-07 20:34 UTC by prayutsu

Added the licenses that can't be scraped directly.

2021-07-07 21:00 UTC, BenHenning requested changes
Thanks @prayutsu. Leaving some follow-up comments.

2021-07-07 21:00 UTC, BenHenning commented on bsd-3-clause-license.txt
> +ASM: a very small and fast Java bytecode manipulation framework
This seems specific to ASM--should this file be named for the specific dependency that needs it, instead?

2021-07-07 21:00 UTC, BenHenning commented on cddl-gpl2-license.txt
> +COMMON DEVELOPMENT AND DISTRIBUTION LICENSE (CDDL) Version 1.1
Which dependencies require these?

2021-07-07 21:00 UTC, BenHenning commented on konfetti-license.txt
> +ISC License
Re: name, I suggest including the whole Maven coordinate minus version to reduce potential ambiguities in the future between different license files.

2021-07-07 21:00 UTC, BenHenning commented on simplified-bds-license.txt
> +Note: This license has also been called the "Simplified BSD License" and the "FreeBSD License". See also the 3-clause BSD License.
Typo in filename: s/bds/bsd

2021-07-07 21:54 UTC, prayutsu commented on cddl-gpl2-license.txt
> +COMMON DEVELOPMENT AND DISTRIBUTION LICENSE (CDDL) Version 1.1
`javax.annotation:javax.annotation-api:1.3.2`

The above dependency requires this.

2021-07-07 21:59 UTC, prayutsu commented on simplified-bds-license.txt
> +Note: This license has also been called the "Simplified BSD License" and the "FreeBSD License". See also the 3-clause BSD License.
Fixed,

2021-07-07 21:59 UTC, prayutsu commented on konfetti-license.txt
> +ISC License
Done.

2021-07-07 22:00 UTC, prayutsu commented on bsd-3-clause-license.txt
> +ASM: a very small and fast Java bytecode manipulation framework
Yup, sounds good.

2021-07-07 22:02 UTC, prayutsu commented on cddl-gpl2-license.txt
> +COMMON DEVELOPMENT AND DISTRIBUTION LICENSE (CDDL) Version 1.1
As only one dependency requires this license, updated the name of the file to be specific to the dependency.

2021-07-08 07:52 UTC, BenHenning approved these changes
Thanks @prayutsu.

2021-07-08 07:52 UTC, BenHenning commented on org.ow2.asm.asm-7.2-license.txt
> +ASM: a very small and fast Java bytecode manipulation framework
We should make sure the filenames are consistent. It seems like the javax one is using the full coordinate, but konfetti and asm are using part.

2021-07-08 07:53 UTC, BenHenning requested changes
Actually requesting changes per the last unresolved comment.

2021-07-08 08:55 UTC, prayutsu commented on org.ow2.asm.asm-7.2-license.txt
> +ASM: a very small and fast Java bytecode manipulation framework
Fixed.

2021-07-08 08:55 UTC, prayutsu commented
@BenHenning PTAL fixed the naming of the 2 licenses.

2021-07-08 10:14 UTC, BenHenning approved these changes
Thanks @prayutsu.

2021-07-08 10:14 UTC, merged